### ISSUE TITLE
DDR5 RFM is not specified

### ISSUE THREAD

**Issue by jyk2498** [CMU-SAFARI/ramulator2#16]
Hi everyone

I modified the 'example_config.yaml' file to run DDR5, but when I try to run it, I encounter the following error message:

`terminate called after throwing an instance of 'Ramulator::ConfigurationError'
  what():  ParamGroup "RFM" is not specified for implementation "DDR5".
Aborted (core dumped)`

How can I resolve this issue?

Thanks.

**Comment by RichardLuo79** [comment]
Hi,

Could you share the YAML configuration file here?

**Comment by ankenman** [comment]
I can reproduce this issue with this config:

```
Frontend:
  impl: GEM5

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 4

  DRAM:
    impl: DDR5
    org:
      preset: DDR5_8Gb_x4
      channel: 1
      rank: 1
    timing:
      preset: DDR5_3200AN

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh
```

**Comment by jyk2498** [comment]
below is the yaml file that I ran:
```
Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 300000
  traces: 
    - example_inst.trace

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR5
    org:
      preset: DDR5_16Gb_x8
      channel: 1
      rank: 2
    timing:
      preset: DDR5_3200AN

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh
```
