### ISSUE TITLE
Invalid bank state error in LPDDR5

### ISSUE THREAD

**Issue by tommarin** [CMU-SAFARI/ramulator2#66]
### Setup
- Master branch + patch #65
- Using a sample configuration script with a SPEC CPU2006 trace:
```
Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 500000
  traces:
    - ../ramulator/cputraces/429.mcf

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: LPDDR5
    org:
      preset: LPDDR5_4Gb_x16
    timing:
      preset: LPDDR5_6400

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh
```
### Issue description
Simulation fails with this error:
`[error] [RowHit::Bank] Invalid bank state for an RD/WR command!`
