### ISSUE TITLE
Incorrect Density for HBM2_8Gb Preset in Memory Configuration

### ISSUE THREAD

**Issue by Ozen7** [CMU-SAFARI/ramulator2#71]
https://github.com/CMU-SAFARI/ramulator2/blob/e62c84a6f0e06566ba6e182d308434b4532068a5/src/dram/impl/HBM2.cpp#L14

Hello, 

The HBM2_8Gb preset defines a density of 6<<10 (6144 Mb or 6 Gb) per channel. However, the preset name (HBM2_8Gb) suggests the density should be 8<<10 (8192 Mb or 8 Gb) per channel. This mismatch leads to errors when using this preset in configurations expecting 8 Gb density.

### Steps to Reproduce
1) Configure Ramulator with the following setup:
```
DRAM:
  impl: HBM2
  org:
    preset: HBM2_8Gb
    channel: 8
    rank: 1
  timing:
    preset: HBM2_2000
```
2) Run a simulation with this configuration.
3) Observe the error indicating a mismatch between the calculated density and the preset density:
`An error occurred: Calculated HBM2 channel density 8192 Mb does not equal the provided density 6144 Mb!`

### Expected Behavior
The HBM2_8Gb preset should define a density of 8<<10 (8192 Mb) per channel, matching the preset name.

Thank you!
